version: "3"

services:
  # web:
  #   image: web
  #   container_name: web
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #   ports:
  #     - 3000:3000
  public_web:
    image: public_web
    container_name: public_web
    build:
      context: .
      dockerfile: ./apps/public_web/Dockerfile
    environment:
      - NODE_ENV=production
      - HOSTNAME=localhost
      - PORT=3000
      - APPLICATION_NAME=
      - BASE_URL=
      - AUTH_URL=
      - PROJECT_SERVICE_URL=
      - APP_NAME=MVC
      - PRIMARY_COLOR=0 100% 43%
      - AUTH_TRUST_HOST=true
      - AUTH_SECRET=
      - NEXTAUTH_SECRET=
      - TEST_USERNAME=
      - TEST_PASSWORD=
    labels: 
      - 'traefik.http.services.public_web.loadbalancer.server.port=3001'
