version: "3"

services:
  # web:
  #   image: web
  #   container_name: web
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - NODE_ENV=production
  public_web:
    image: public_web
    container_name: public_web
    build:
      context: .
      dockerfile: ./apps/public_web/Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3001"
    labels: 
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-eos8okgc8ccgskocg8os4gss-public_web.entryPoints=http
      - traefik.http.routers.https-0-eos8okgc8ccgskocg8os4gss-public_web.entryPoints=https
      - traefik.http.routers.http-0-eos8okgc8ccgskocg8os4gss-public_web.middlewares=gzip,redirect-to-https
      - traefik.http.routers.https-0-eos8okgc8ccgskocg8os4gss-public_web.middlewares=gzip
      - 'traefik.http.services.public_web.loadbalancer.server.port=3001'
