version: "3"

services:
  # web:
  #   image: web
  #   container_name: web
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #   ports:
  #     - 3000:3000
  public_web:
    image: public_web
    container_name: public_web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    environment:
      - NODE_ENV=production
      - HOSTNAME=${HOSTNAME:-localhost}
      - PORT=${PORT:-3000}
      - APPLICATION_NAME=${APPLICATION_NAME:-}
      - BASE_URL=${BASE_URL:-}
      - AUTH_URL=${AUTH_URL:-}
      - PROJECT_SERVICE_URL=${PROJECT_SERVICE_URL:-}
      - APP_NAME=${APP_NAME:-MVC}
      - PRIMARY_COLOR=${PRIMARY_COLOR:-0 100% 43%}
      - AUTH_TRUST_HOST=${AUTH_TRUST_HOST:-true}
      - AUTH_SECRET=${AUTH_SECRET:-}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-}
      - TEST_USERNAME=${TEST_USERNAME:-}
      - TEST_PASSWORD=${TEST_PASSWORD:-}
    labels: 
      - 'traefik.http.services.web.loadbalancer.server.port=3000'
